classDiagram
    Estacionamiento *-- PlantadeEstacionamiento
    PlantadeEstacionamiento *-- Slots
    Slots o-- Vehiculo
    PlantadeEstacionamiento *-- PaneldeEstacionamiento
    
    Sistema *-- Estacionamiento
    Sistema *-- Usuario
    Sistema *-- TicketEstacionamiento
    Sistema *-- PortalAsistenteEstacionamiento
    Sistema *-- PortalInformacionCliente
    Sistema *-- PanelElectrico

    Slots <|-- Discapacitado
    Slots <|-- Compacto
    Slots <|-- Grande
    Slots <|-- Motocicleta
    Slots <|-- Electrico
    
    Usuario <|-- Administrador
    Usuario <|-- Cliente
    Usuario <|-- Asistente
    
    Asistente <-- PortalAsistenteEstacionamiento

    Cliente *-- TicketEstacionamiento

    TicketEstacionamiento <|-- TicketPanelEntrada
    TicketEstacionamiento <|-- TicketPanelSalida
    TicketEstacionamiento *-- Vehiculo

    TicketPanelSalida *-- Asistente
    TicketPanelSalida *-- Pago
    TicketPanelSalida o-- PortalInformacionCliente    

    PortalInformacionCliente <-- Pago

    PanelElectrico <-- Pago

    Pago <|-- Tarifa

    class Sistema
    Sistema: +Usuarios
    Sistema: +Tickets
    Sistema: +Estacionamiento
    Sistema: +PortalAsistenteEstacionamiento
    Sistema: +PortalInformacionCliente
    Sistema: +PanelElectrico
    Sistema: CrearUsuario()
    Sistema: EliminarUsuario()
    Sistema: EmitirTicket()

    class Estacionamiento
    Estacionamiento: +Nombre
    Estacionamiento: +Direccion
    Estacionamiento: +PlantasdeEstacionamiento
    Estacionamiento: Estacionamiento()


    class PlantadeEstacionamiento
    PlantadeEstacionamiento: +Nro-Piso
    PlantadeEstacionamiento: +Slots
    PlantadeEstacionamiento: +Estado
    PlantadeEstacionamiento: +Ubicacion
    PlantadeEstacionamiento: +Vehiculo

    class Slots
    Slots: +Discapacitado
    Slots: +Compacto
    Slots: +Compacto
    Slots: +Grande
    Slots: +Motocicleta
    
    class Discapacitado

    class Compacto
    
    class Grande
    
    class Motocicleta
    
    class Electrico
    Electrico: +Carga

    class Vehiculo
    Vehiculo: +Automovil
    Vehiculo: +Camion
    Vehiculo: +Electrico
    Vehiculo: +Camioneta
    Vehiculo: +Motocicleta

    class Usuario
    Usuario: +Usuarios
    Usuario: CreaciondeCuentas()

    class Administrador
    Administrador: +Administrador
    
    class Cliente
    Cliente: +Cliente

    class TicketEstacionamiento
    TicketEstacionamiento: +TicketEntrada
    TicketEstacionamiento: +TicketSalida
    TicketEstacionamiento: TicketEstacionamiento()
    TicketEstacionamiento: Cliente()

    class TicketPanelEntrada
    TicketPanelEntrada: +TicketEntrada
    TicketPanelEntrada: EmitirTicketEntrada()

    class TicketPanelSalida
    TicketPanelSalida: +TicketSalida
    TicketPanelSalida: +PagoTarifa
    TicketPanelSalida: PagarTarifadeEstacionamiento()

    class Pago
    Pago: +TarjetaCredito
    Pago: +Efectivo
    Pago: +Monto

    class Tarifa
    Tarifa: +TarifaEstacionamiento-1hora
    Tarifa: +TarifaEstacionamiento-2hora
    Tarifa: +TarifaEstacionamiento-3hora
    Tarifa: +TarifaEstacionamiento-HorasRestantes
    Tarifa: CalcularMontoHorasTarifa()

    class PaneldeEstacionamiento
    PaneldeEstacionamiento: +DisponibilidadAparcamientoLibre

    class PortalAsistenteEstacionamiento
    PortalAsistenteEstacionamiento: +EscaneoTicket
    PortalAsistenteEstacionamiento: +ProcesodePago

    class PortalInformacionCliente
    PortalInformacionCliente: +PagoTarifa
    PortalInformacionCliente: +ActualizacionTicket

    class PanelElectrico
    PanelElectrico: +PagoCarga
    PanelElectrico: +CargaElectrico

    class Asistente
    Asistente: +TarjetaCredito
    Asistente: +Efectivo
