classDiagram
    Estacionamiento *-- PlantadeEstacionamiento
    PlantadeEstacionamiento *-- Slot
    Slot o-- Vehiculo
    PlantadeEstacionamiento *-- PaneldeEstacionamiento
    
    Sistema *-- Estacionamiento
    Sistema *-- TicketEstacionamiento
    Sistema *-- PortalAsistenteEstacionamiento
    Sistema *-- PortalInformacionCliente
    Sistema *-- PanelElectrico

    Slot <|-- Discapacitado
    Slot <|-- Compacto
    Slot <|-- Grande
    Slot <|-- Motocicleta
    Slot <|-- Electrico
    
    Sistema <|-- Administrador
    Sistema <|-- Cliente
    Sistema <|-- Asistente
    
    Asistente --> PortalAsistenteEstacionamiento

    Cliente *-- TicketEstacionamiento

    TicketEstacionamiento *-- PanelEntrada
    TicketEstacionamiento *-- PanelSalida
    TicketEstacionamiento *-- Vehiculo

    PanelSalida *-- Asistente
    PanelSalida *-- Pago
    PanelSalida <|-- PortalInformacionCliente    

    PortalInformacionCliente <-- Pago

    PanelElectrico <-- Pago

    Pago <|-- Tarifa

    class Sistema
    Sistema: +Usuarios
    Sistema: +Tickets
    Sistema: +Estacionamiento
    Sistema: +PortalAsistenteEstacionamiento
    Sistema: +PortalInformacionCliente
    Sistema: +PanelElectrico
    Sistema: CrearUsuario()
    Sistema: EliminarUsuario()
    Sistema: EmitirTicket()

    class Estacionamiento
    Estacionamiento: +Nombre
    Estacionamiento: +Direccion
    Estacionamiento: +PlantasdeEstacionamiento

    class PlantadeEstacionamiento
    PlantadeEstacionamiento: +Nro-Piso
    PlantadeEstacionamiento: +Slots
    PlantadeEstacionamiento: +Estado
    PlantadeEstacionamiento: +Ubicacion
    PlantadeEstacionamiento: +Vehiculo

    class Slot
    Slot: +Discapacitado
    Slot: +Compacto
    Slot: +Grande
    Slot: +Motocicleta
    Slot: +Electrico
    
    class Discapacitado

    class Compacto
    
    class Grande
    
    class Motocicleta
    
    class Electrico
    Electrico: +Carga

    class Vehiculo
    Vehiculo: +Automovil
    Vehiculo: +Camion
    Vehiculo: +Electrico
    Vehiculo: +Camioneta
    Vehiculo: +Motocicleta

    class Administrador
    Administrador: +Id
    Administrador: +Nombre
    Administrador: +Contraseña
    Administrador: AgregarPisos()
    Administrador: ModificarPisos()
    Administrador: ModificarLugares()
    Administrador: ModificarPanelesEntrada()
    Administrador: ModificarPanelesSalida()
    Administrador: AgregarAsistentes()
    Administrador: EliminarAsistentes()

    class Asistente
    Asistente: +Id
    Asistente: +Nombre
    Asistente: +Contraseña
    Asistente: +TarjetaCredito
    Asistente: +Efectivo
    
    class Cliente
    Cliente: +Ticket
    Cliente: PagarTicket()
    Cliente: PagarPanelElectrico()

    class TicketEstacionamiento
    TicketEstacionamiento: +TicketEntrada

    class PanelEntrada
    PanelEntrada: +TicketEntrada
    PanelEntrada: ImprimirTicketEntrada()

    class PanelSalida
    PanelSalida: +TicketSalida
    PanelSalida: +PagoTarifa
    PanelSalida: PagarTarifadeEstacionamiento()
    PanelSalida: ActualizarTicket()

    class Pago
    Pago: +TarjetaCredito
    Pago: +Efectivo
    Pago: +Monto

    class Tarifa
    Tarifa: +TarifaEstacionamiento-1hora
    Tarifa: +TarifaEstacionamiento-2hora
    Tarifa: +TarifaEstacionamiento-3hora
    Tarifa: +TarifaEstacionamiento-HorasRestantes
    Tarifa: CalcularMontoHorasTarifa()

    class PaneldeEstacionamiento
    PaneldeEstacionamiento: +DisponibilidadAparcamientoLibre

    class PortalAsistenteEstacionamiento
    PortalAsistenteEstacionamiento: EscaneoTicket()
    PortalAsistenteEstacionamiento: ProcesodePago()

    class PortalInformacionCliente
    PortalInformacionCliente: +PagoTarifa
    PortalInformacionCliente: +ActualizacionTicket
    PortalInformacionCliente: PagarTarifadeEstacionamiento()

    class PanelElectrico
    PanelElectrico: +PagoCarga
    PanelElectrico: +CargaElectrico
